;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Personagem.Dano.DanoRecebido",NewTagName="Personagem.Dano.Fraco")
+GameplayTagRedirects=(OldTagName="Personagem.Dano.Fraco",NewTagName="Personagem.Empurrão.Fraco")
+GameplayTagRedirects=(OldTagName="Personagem.Dano",NewTagName="Personagem.Empurrão")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão.Fraco",NewTagName="Personagem.Empurrão.1")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão.1",NewTagName="Personagem.Empurrão.Derruba")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão.2",NewTagName="Personagem.Empurrão.NãoDerruba")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão.Derruba",NewTagName="Personagem.Reação.Derruba")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão.NãoDerruba",NewTagName="Personagem.Reação.NãoDerruba")
+GameplayTagRedirects=(OldTagName="Personagem.Empurrão",NewTagName="Personagem.Reação")
+GameplayTagRedirects=(OldTagName="Personagem.Estado.PodeSeMovimentar",NewTagName="Personagem.Estado.NãoPodeSeMovimentar")
+GameplayTagRedirects=(OldTagName="Personagem.Estado.NoAr",NewTagName="Jogador.Estado.NoAr")
+GameplayTagRedirects=(OldTagName="Personagem.Estado.NoChão",NewTagName="Jogador.Estado.NoChão")
+GameplayTagRedirects=(OldTagName="Personagem.Estado.NãoPodeSeMovimentar",NewTagName="Jogador.Estado.NãoPodeSeMovimentar")
+GameplayTagRedirects=(OldTagName="Personagem.Estado.UsandoHabilidade",NewTagName="Jogador.Estado.UsandoHabilidade")
+GameplayTagRedirects=(OldTagName="Personagem.Estado",NewTagName="Jogador.Estado")
+GameplayTagRedirects=(OldTagName="Personagem.Input.Baixo",NewTagName="Jogador.Input.Baixo")
+GameplayTagRedirects=(OldTagName="Personagem.Input.Cima",NewTagName="Jogador.Input.Cima")
+GameplayTagRedirects=(OldTagName="Personagem.Input.Direita",NewTagName="Jogador.Input.Direita")
+GameplayTagRedirects=(OldTagName="Personagem.Input.Esquerda",NewTagName="Jogador.Input.Esquerda")
+GameplayTagRedirects=(OldTagName="Personagem.Input",NewTagName="Jogador.Input")
+GameplayTagRedirects=(OldTagName="Personagem.Reação.Derruba",NewTagName="Jogador.Reação.Derruba")
+GameplayTagRedirects=(OldTagName="Personagem.Reação.JogarProAlto",NewTagName="Jogador.Reação.JogarProAlto")
+GameplayTagRedirects=(OldTagName="Personagem.Reação.NãoDerruba",NewTagName="Jogador.Reação.NãoDerruba")
+GameplayTagRedirects=(OldTagName="Personagem.Reação",NewTagName="Jogador.Reação")
+GameplayTagRedirects=(OldTagName="Personagem",NewTagName="Jogador")
+GameplayTagList=(Tag="GameplayCue.Contato.Raio",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Área.Corte",DevComment="")

